CREATE DATABASE ZW7DOR;
USE ZW7DOR;
CREATE TABLE GYARTO(adoszam INT PRIMARY KEY, nev CHAR(30) NOT NULL, telephely CHAR(50));
CREATE TABLE TERMEK(tkod INT PRIMARY KEY, nev CHAR(30) NOT NULL, ear INT CHECK(ear>0), gyarto INT REFERENCES GYARTO);
CREATE TABLE EGYSEGEK(aru INT REFERENCES TERMEK, db INT CHECK(db>0));
CREATE TABLE ALKATRESZ(akod INT PRIMARY KEY, nev CHAR(30) NOT NULL);
CREATE TABLE KOMPONENS(termek INT REFERENCES TERMEK, alkatresz INT REFERENCES ALKATRESZ);